# Create user

POST ec2-18-141-12-199.ap-southeast-1.compute.amazonaws.com:8081/users
content-type: application/json

{
    "user_name": "an.nguyen",
    "full_name": "nguyent the an",
    "mail": "annguyenthe.master@gmail.com",
    "role": "user"
}

###
# Get user
GET ec2-18-141-12-199.ap-southeast-1.compute.amazonaws.com:8081/user/15

###
# Get list users
GET ec2-18-141-12-199.ap-southeast-1.compute.amazonaws.com:8081/users?page_id=1&page_size=5

###
# Login users
POST ec2-18-141-12-199.ap-southeast-1.compute.amazonaws.com:8081/login
content-type: application/json

{
    "user_name": "an.nguyen",
    "mail": "annguyenthe.master@gmail.com"
}

###
# Verify OTP
POST ec2-18-141-12-199.ap-southeast-1.compute.amazonaws.com:8081/otp
content-type: application/json

{
    "user_name": "an.nguyen",
    "mail": "annguyenthe.master@gmail.com",
    "otp": "859584"
}
