// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"
)

type User struct {
	ID        int64     `json:"id"`
	UserName  string    `json:"user_name"`
	FullName  string    `json:"full_name"`
	Mail      string    `json:"mail"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}
