// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    user_name,
    full_name,
    mail,
    role
) VALUES (
    $1, $2, $3, $4
) RETURNING id, user_name, full_name, mail, role, created_at
`

type CreateUserParams struct {
	UserName string `json:"user_name"`
	FullName string `json:"full_name"`
	Mail     string `json:"mail"`
	Role     string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.UserName,
		arg.FullName,
		arg.Mail,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.FullName,
		&i.Mail,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, user_name, full_name, mail, role, created_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.FullName,
		&i.Mail,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUserName = `-- name: GetUserByUserName :one
SELECT id, user_name, full_name, mail, role, created_at FROM users
WHERE user_name = $1 LIMIT 1
`

func (q *Queries) GetUserByUserName(ctx context.Context, userName string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUserName, userName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.FullName,
		&i.Mail,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, user_name, full_name, mail, role, created_at FROM users
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.FullName,
			&i.Mail,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGmailUser = `-- name: UpdateGmailUser :one
UPDATE users
SET mail = $2
WHERE id = $1
RETURNING id, user_name, full_name, mail, role, created_at
`

type UpdateGmailUserParams struct {
	ID   int64  `json:"id"`
	Mail string `json:"mail"`
}

func (q *Queries) UpdateGmailUser(ctx context.Context, arg UpdateGmailUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateGmailUser, arg.ID, arg.Mail)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.FullName,
		&i.Mail,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
